### ISSUE TITLE
roxenvbash is not installed correctly

### ISSUE THREAD

**Issue by jcrivenaes** [equinor/subscript#163]
Not sure of this is a `subscript` issue or a `Komodo` issue...

roxenbash is script that sets a Roxar API environments, hence it need to be `sourced`:

```
which roxenvbash
/prog/res/komodo/2020.07.05-py27/root/bin/roxenvbash

source roxenvbash
bash: ./../libexec/bash: No such file or directory

# rather this works (note libexec instead of root):
source /prog/res/komodo/2020.07.05-py27/root/libexec/roxenvbash
```

**Comment by berland** [comment]
What is the status on this issue?

**Comment by jcrivenaes** [comment]
Works in Komodo testing. The remaining issue is that this easily gets out of date and perhaps need to split out settings as outside of the script...

**Comment by berland** [comment]
AFAIK, not to be solved in subscript?

**Comment by jcrivenaes** [comment]
We should consider taking out `roxenvbash `and `runrms `from `subscript `and Komodo and leave it to the GBS SUB team (those responsible for installing RMS). There it could  have a "komodo'ish" setup targeted for RMS and it's python env.

**Comment by berland** [comment]
Closing as "wontfix" for subscript.
