### ISSUE TITLE
Port check_ecl_initialization from resscript

### ISSUE THREAD

**Issue by berland** [equinor/subscript#24]
check_ecl_initializization is missing resscript.header. Unknown usage, but seen in recent ERT configs.

**Comment by asnyv** [comment]
@berland Even if the porting is `wontfix`, should we maybe make an issue for a proper `subscript` version of this? Haven't looked much into `eclOutput` and `ecl_parse` in resscript, but from the naming it sounds like something `opm-common` might cover fairly well now?

**Comment by berland** [comment]
Yes, the functionality that `check_ecl_initialization` provided is still relevant I suppose.

**Comment by asnyv** [comment]
Yes, for sure!
