### ISSUE TITLE
[eclcompress] detect if file is binary grdecl and skip

### ISSUE THREAD

**Issue by jcrivenaes** [equinor/subscript#243]
When export from RMS is binary grdecl, eclcompress on that file should be skipped. 

This is a case since binary grdecl is not supported for all Eclipse keywords, and "mixed-exports" will occur.

See if it is possible for eclcompress to quickly detect if file is binary an just omit any actions. Perhaps like this: https://stackoverflow.com/a/30273352

**Comment by berland** [comment]
Example needed.
