### ISSUE TITLE
PRTVOL2CSV fails when mix of names and numbers defined in region2fipnum.

### ISSUE THREAD

**Issue by mareco701** [equinor/subscript#247]
when having a mix of names and numbers in the region2fipnum.yaml file (see example below where one of the region is named by a number) then the script fails with following error message which is not really explicit:
 
![image](https://user-images.githubusercontent.com/70753366/100238723-d0073100-2f30-11eb-9544-141348f6dc87.png)

![image](https://user-images.githubusercontent.com/70753366/100238795-e9a87880-2f30-11eb-9765-0212637f56b5.png)

should be fixed or just get a clearer error message

**Comment by berland** [comment]
@mareco701 , are  you able to  test if this bug  has been resolved? (through virtual env or komodo bleeding)

**Comment by mareco701** [comment]
Hi, yes, I tested it and it now generates a file named by default rft_ertobs_sim.csv.

**Comment by mareco701** [comment]
Hi, sorry the answer before was not for this... but I have now tested prtvol2csv with the regions mix set which failed but now works fine with the fix.
