### ISSUE TITLE
FMUOBS unable to parse GENERAL_OBSERVATION

### ISSUE THREAD

**Issue by eivindsm** [equinor/subscript#259]
I fail to convert GENERAL_OBSERVATIONS from an ert observation file. As shown below:

(kenv_2020.11 + 2020.11.00-py36-rhel7) eism@st-linrgsn198:/project/fmu/users/eism/reek_hm/r006/ert/input/observations> fmuobs -o gen_obs.yml gen_obs.txt 
ERROR:subscript.fmuobs:None of your observations are supported in YAML
(kenv_2020.11 + 2020.11.00-py36-rhel7) eism@st-linrgsn198:/project/fmu/users/eism/reek_hm/r006/ert/input/observations> more gen_obs.yml 
{}
(kenv_2020.11 + 2020.11.00-py36-rhel7) eism@st-linrgsn198:/project/fmu/users/eism/reek_hm/r006/ert/input/observations> more gen_obs.txt 
 
-- RFT data

GENERAL_OBSERVATION     RWI_2_OBS     {   DATA=  RWI_2_SIM  ;  RESTART=1; OBS_FILE= ./rft/RWI_2.obs  ; };
GENERAL_OBSERVATION     ROP_5_OBS     {   DATA=  ROP_5_SIM  ;  RESTART=1; OBS_FILE= ./rft/ROP_5.obs  ; };
GENERAL_OBSERVATION     RWI_3_OBS     {   DATA=  RWI_3_SIM  ;  RESTART=1; OBS_FILE= ./rft/RWI_3.obs  ; };
GENERAL_OBSERVATION     ROP_4_OBS     {   DATA=  ROP_4_SIM  ;  RESTART=1; OBS_FILE= ./rft/ROP_4.obs  ; };

**Comment by berland** [comment]
The  YAML format does not specify how GENERAL_OBSERVATION should look like, and export of these to yaml is thus not currently supported.
