### ISSUE TITLE
[pack_sim] make able to parse decks containing æøå 

### ISSUE THREAD

**Issue by eivindsm** [equinor/subscript#299]
After upgrading to py-3 pack_sim is unable to parse decks containing exoteric characters like øæå. Program crashes with a message like 'utf-8' codec can't decode byte 0xc5 in position, which does not make much sense for may users. As of now users are recommended to edit their decks before packing, but I think it would make good sense to make the script robust with respect to this.

**Comment by berland** [comment]
This is a tough decision. 

We do want to get rid of every ISO-8859-15 encoded text file in our projects after the Python 3 upgrade.
Python3 has decided against precisely this, letting encoding errors pass through and let something else deal with the consequences.

Some alternatives:
* Assume all UnicodeDecodeErrors stem from ISO-8859-15 files and automatically reinterpret failed files as such. This sounds a little bit dangerous, and will keep wrongly encoded files on disk. They will then later fail when fed into other Py3 code.
* Catch the exception, and provide a easier to understand errror message (giving exact filename, and file contents surrounding the erroneous byte).

Both of these require some commitment, and if done, must be implemented broadly in all scripts parsing user files, both in subscript and in ecl2df and probably many more.

**Comment by eivindsm** [comment]
I agree, what makes me inclined to consider some sort of support is that most often these characters are in comments. Maybe we could consider exception handling for comments and pass errors for input which is not recognized as such. Not sure how to efficiently implement this for our entire software stack, though.
