### ISSUE TITLE
[fmuobs] verbose argument working as intended?

### ISSUE THREAD

**Issue by rnyb** [equinor/subscript#368]
When running fmuobs without `--verbose` there are still a lot of info printed to terminal. Would it be possible to avoid all this print to terminal?

**Comment by berland** [comment]
Not able to reproduce locally. Which komodo version? Can  you also test with komodo bleeding, as there has been changes to whether logging is printed to stdout and stderr?

**Comment by berland** [comment]
The intention of the `--verbose` option is to print more output (to `stdout`). If you don't include it, nothing is printed if no warnings are issued. 

The suggested ERT workflow configuration includes `--verbose`; https://github.com/equinor/subscript/blob/cdcc81afb1662b1199286b8bf31f7143b4d9f026/src/subscript/fmuobs/fmuobs.py#L60 

So you are saying that you have removed `--verbose` from this configuration file in your setup, and stdout files are still filled with this output?

**Comment by rnyb** [comment]
> The intention of the `--verbose` option is to print more output (to `stdout`). If you don't include it, nothing is printed if no warnings are issued.
> 
> The suggested ERT workflow configuration includes `--verbose`;
> 
> https://github.com/equinor/subscript/blob/cdcc81afb1662b1199286b8bf31f7143b4d9f026/src/subscript/fmuobs/fmuobs.py#L60
> 
> So you are saying that you have removed `--verbose` from this configuration file in your setup, and stdout files are still filled with this output?

Yes, correct, i have removed --verbose
