### ISSUE TITLE
[eclcompress] Too much whitespace added

### ISSUE THREAD

**Issue by erlid** [equinor/subscript#408]
**What**
ECLCOMPRESS inserts empty lines 

**How To Reproduce**
Steps to reproduce the behaviour:
```
mkdir -p eclipse/include/grid
cd eclipse/include/grid
printf "MULTIPLY\n 'PORO' 2 /\n/\n" > TEST.INC
cd ../../..
cat eclipse/include/grid/TEST.INC
eclcompress "--files" "__NONE__"
cat eclipse/include/grid/TEST.INC

```

**Proposed Solution** 
_(my first entry on github = have no idea how to do anything here)_
Lines 87 and 92:
Replace
```filelines = fileh.readlines()```
with
```filelines = [line.rstrip() for line in fileh.readlines()]```

**Comment by berland** [comment]
```
$ cat eclipse/include/grid/TEST.INC
-- File compressed with eclcompress at 2021-08-10 08:16:24.478777
-- Compression ratio 1.0 (higher is better, 1 is no compression)

MULTIPLY

  'PORO' 2 /
/

```
