### ISSUE TITLE
roxenvbash assumes SDP_cshrc

### ISSUE THREAD

**Issue by berland** [equinor/subscript#421]
In the line

https://github.com/equinor/subscript/blob/d6132b752f4a14b8b3fedeb99b30c80f83c6e2fe/src/subscript/legacy/roxenvbash#L14

a reference is made to the environment variables that existed while `SDP_cshrc` was in use. This is no longer true, and this script emits the error:
```
[havb@st-linrgsn110:~]$ roxenvbash
/prog/res/komodo/2021.09.rc1-py36-rhel7/root/bin/roxenvbash: line 14: /get_os_version: No such file or directory
```

**Comment by jcrivenaes** [comment]
We never got `roxenvbash` run very well from subscript/komodo. So there is an updated version in `/project/res/roxapi/aux/roxenvbash` which I recommend for those (very few) that need this.

I think we shall remove `roxenvbash ` from subscript and maintain in in the `rms-sys` repo instead, along with `runrms` there.  (There is ongoing work on this in `rms-sys`)

**Comment by berland** [comment]
Removal sounds correct
