### ISSUE TITLE
Remove make_3dgrid_regions

### ISSUE THREAD

**Issue by berland** [equinor/subscript#422]
Is it time to actually do this?

https://github.com/equinor/subscript/blob/d6132b752f4a14b8b3fedeb99b30c80f83c6e2fe/src/subscript/legacy/make_3dgrid_regions#L19

**Comment by jcrivenaes** [comment]
Not sure. Two approaches:
* Leave as is, no big deal and no maintenance needed as long a RHEL7 is stable
* Remove, but be able to roll back if still urgent for some projects

**Comment by berland** [comment]
Leave as is.
