### ISSUE TITLE
Library requirement issue

### ISSUE THREAD

**Issue by alifbe** [equinor/subscript#458]
I am having issue with the library requirement.

When I tried to run casegen_upcars, I got this:

<pre>[kenv + 2021.11.02-py36-rhel7] [alifb@st-linrgs276 casegen]$ casegen_upcars
Traceback (most recent call last):
  File &quot;/project/tooltest/users/alifb/casegen/kenv/root/lib64/python3.6/site-packages/pkg_resources/__init__.py&quot;, line 583, in _build_master
    ws.require(__requires__)
  File &quot;/project/tooltest/users/alifb/casegen/kenv/root/lib64/python3.6/site-packages/pkg_resources/__init__.py&quot;, line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File &quot;/project/tooltest/users/alifb/casegen/kenv/root/lib64/python3.6/site-packages/pkg_resources/__init__.py&quot;, line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (starlette 0.16.0 (/project/tooltest/users/alifb/casegen/kenv/root/lib/python3.6/site-packages), Requirement.parse(&apos;starlette==0.14.2&apos;), {&apos;ert-storage&apos;})
</pre>

I tried to downgrade starlette to 0.14.2 and got this error message:

<pre>[kenv + 2021.11.02-py36-rhel7] [alifb@st-linrgs276 casegen]$ python -m pip install starlette==0.14.2
Collecting starlette==0.14.2
  Using cached starlette-0.14.2-py3-none-any.whl (60 kB)
Installing collected packages: starlette
  Attempting uninstall: starlette
    Found existing installation: starlette 0.16.0
    Uninstalling starlette-0.16.0:
      Successfully uninstalled starlette-0.16.0
<font color="#CC0000">ERROR: pip&apos;s dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.</font>
<font color="#CC0000">fastapi 0.70.0 requires starlette==0.16.0, but you have starlette 0.14.2 which is incompatible.</font>
Successfully installed starlette-0.14.2
</pre>

and when I tried to run casegen_upcars again:
<pre>[kenv + 2021.11.02-py36-rhel7] [alifb@st-linrgs276 casegen]$ casegen_upcars
Traceback (most recent call last):
  File &quot;/project/tooltest/users/alifb/casegen/kenv/root/lib64/python3.6/site-packages/pkg_resources/__init__.py&quot;, line 583, in _build_master
    ws.require(__requires__)
  File &quot;/project/tooltest/users/alifb/casegen/kenv/root/lib64/python3.6/site-packages/pkg_resources/__init__.py&quot;, line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File &quot;/project/tooltest/users/alifb/casegen/kenv/root/lib64/python3.6/site-packages/pkg_resources/__init__.py&quot;, line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (starlette 0.14.2 (/project/tooltest/users/alifb/casegen/kenv/root/lib/python3.6/site-packages), Requirement.parse(&apos;starlette==0.16.0&apos;), {&apos;fastapi&apos;})
</pre>

**Comment by berland** [comment]
This is related to `starlette` in `ert`, for which problems have been solved.
