### ISSUE TITLE
[ri_wellmod] wrapper is not always initialized

### ISSUE THREAD

**Issue by berland** [equinor/subscript#461]
A `wrapper=False` is missing in this function, so whenever `wrapper` is not True, this line given an UnboundLocalError:

https://github.com/equinor/subscript/blob/5e159d191f393ef058e29c64f57ad9fbfd6f1156/src/subscript/ri_wellmod/ri_wellmod.py#L267

**Comment by vkip** [comment]
Closed by #465 (commit https://github.com/equinor/subscript/commit/705254ce4b8c11b2737eafe55c6a9f4af7ae3f40)
