### ISSUE TITLE
Ensure DD/MM/YYYY is preferred over MM/DD/YYYY in fmuobs

### ISSUE THREAD

**Issue by berland** [equinor/subscript#462]
The option `dayfirst=True` can be added to `to_datetime()` in `fmuobs` to make it more robust in terms of expected date formats used in ERT. This might make it possible to parse "01/04/2001 03:12:00" as a datetime for an observation "correctly".

https://github.com/equinor/subscript/blob/5e159d191f393ef058e29c64f57ad9fbfd6f1156/src/subscript/fmuobs/parsers.py#L438

**Comment by berland** [comment]
Context: https://app.slack.com/client/T02JL00JU/CDPJULWR4

**Comment by asnyv** [comment]
should we just close this now that ERT strictly requires ISO formatted dates (YYYY-MM-DD)?
