### ISSUE TITLE
INTERP_RELPERM:  apply root_path to pyscalfile-entry

### ISSUE THREAD

**Issue by bkhegstad** [equinor/subscript#473]
hig, low and base uses root-path. This makes it compatible with FMU using local paths. pyscalfile, however, is not affected by root-path making it necessary with absolute path in many cases. This is not in the spirit of FMU.

Please add pyscalfile to the `prepend_root_path_to_relative_files`-function.

**Comment by asnyv** [comment]
Closed by #475
