### ISSUE TITLE
Implement script for calculating CO2 volume inside/outside a polygon boundary

### ISSUE THREAD

**Issue by vegardkv** [equinor/subscript#502]
This addresses a specific script that already exists for post-processing simulation results from the Pflotran simulator.

Input is a result from a simulation run, which follow the same format as Eclipse (EGRID, UNRST and INIT files), as well as a polygon file (csv).

Output is a table containing the amount of CO2 (kg) inside/outside the provided polygon, with one row per time step.

If subscript is not the appropriate repo for this script, it would be nice to have discussion if there are other repos that are better suited.

**Comment by mferrera** [comment]
Merged!
