### ISSUE TITLE
[sector2fluxnum] Default eclipse version should be bumped

### ISSUE THREAD

**Issue by berland** [equinor/subscript#512]
sector2fluxnum uses Eclipse version 2014.2 by default in tests:
https://github.com/equinor/subscript/blob/master/tests/test_sector2fluxnum.py#L39

and is also a default in the code
https://github.com/equinor/subscript/blob/b6c2e076946487a7d8f663ab3b1f75f8c41fc446/src/subscript/sector2fluxnum/datafile_obj.py#L393

This Eclipse version is not available in the Azure compute nodes, and must be bumped.

**Comment by alifbe** [comment]
@berland which Eclipse version do you prefer to have?
