### ISSUE TITLE
subscript register FmuObs as a ert plugin, but ert expects all plugins to derive from ErtPlugin

### ISSUE THREAD

**Issue by eivindjahren** [equinor/subscript#514]
https://github.com/equinor/subscript/blob/26913d760d8ca3e6d6d3f2bf7ca097137415367c/setup.py#L42-L47 but the ert expects all plugins to derive from ErtPlugin: https://github.com/equinor/ert/blob/04c102b8d57c16a771ebe061aad63bc5f2a0f87a/src/ert/_c_wrappers/job_queue/ert_plugin.py#L8-L17

This results in the following failure when opening the Ert gui:
```
ert/gui/tools/plugins/plugin.py", line 22, in __init__
    self.__name = script.getName()
ERT crashed unexpectedly with "'FmuObs' object has no attribute 'getName'".
```

**Comment by mferrera** [comment]
Confirmed that this is no longer an issue
