### ISSUE TITLE
[fmuobs] Support ERT ISO format dates

### ISSUE THREAD

**Issue by asnyv** [equinor/subscript#515]
Default ERT date format is now ISO (YYYY-MM-DD). DD/MM/YYYY is deprecated in ERT (https://github.com/equinor/ert/pull/3958)

Should probably handle the deprecated formats for parsing until no longer supported by ERT. Export should be to ISO only.

**Comment by berland** [comment]
Resolved in #507

**Comment by asnyv** [comment]
Ah, nice @berland! I only searched the issue list, not PRs 😅 ready for review?
