### ISSUE TITLE
test_csv2ofmvol incompatible with Pandas 2.0.0

### ISSUE THREAD

**Issue by berland** [equinor/subscript#525]
There is a test failure when `pandas==2.0.0`:

```
$ pytest -sxv tests/test_csv2ofmvol.py::test_df2vol[dframe6-expected_lines6]
[snip]
        backagain_df = ofmvol2csv.process_volstr(volstr)
        if dframe.empty:
            assert backagain_df.empty
        else:
            # (bogus columns in dframe must be ignored)
>           pd.testing.assert_frame_equal(
                dframe[backagain_df.columns].fillna(value=0.0), backagain_df
            )

tests/test_csv2ofmvol.py:288: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pandas/_libs/testing.pyx:52: in pandas._libs.testing.assert_almost_equal
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   AssertionError: MultiIndex level [1] are different
E   
E   MultiIndex level [1] values are different (50.0 %)
E   [left]:  DatetimeIndex(['2010-01-01', '2010-01-02'], dtype='datetime64[ns]', name='DATE', freq=None)
E   [right]: DatetimeIndex(['2010-01-01', '2010-02-01'], dtype='datetime64[ns]', name='DATE', freq=None)
E   At positional index 1, first diff: 2010-01-02T00:00:00.000000000 != 2010-02-01T00:00:00.000000000

pandas/_libs/testing.pyx:172: AssertionError
================================================================================== short test summary info ===================================================================================
FAILED tests/test_csv2ofmvol.py::test_df2vol[dframe6-expected_lines6] - AssertionError: MultiIndex level [1] are different

```

**Comment by alifbe** [comment]
@berland thanks for reporting.

It seems like `pd.to_datetime` change its behavior with pandas 2.0 but I cannot find any documentation about it.

Pandas 2.0
````
>>> pd.to_datetime("2010-01-02", dayfirst=True).strftime("%d %b %y")
'01 Feb 10'
````

Pandas 1.5.3
````
>>> pd.to_datetime("2010-01-02", dayfirst=True).strftime("%d %b %y")
'02 Jan 10'
````

It's not obvious from this test dataset which one is correct. but intuitively, I think Pandas 2.0 behavior is the correct one. Any clue what is the preferred date format for this tool @berland ?

https://github.com/equinor/subscript/blob/87c74b52819d90057bd9690c7f2db75152840759/tests/test_csv2ofmvol.py#L223-L241

**Comment by berland** [comment]
Nice catch. 

It seems that `dayfirst=True` is ignored when parsing dates that are already ISO-8601 in Pandas 1.5.3, while in Pandas 2.0.0 it actually uses `dayfirst=True`. One could argue that is a bug in Pandas 1.5.3 (but the real problem lies in the ambiguity in non-ISO dates).  In the documentation for `to_datetime` there is a warning on `dayfirst`: 
> `dayfirst=True` is not strict, but will prefer to parse with day first.

**Comment by berland** [comment]
At first glance, I would speculate this change is from https://github.com/pandas-dev/pandas/commit/d1095bcd5a43528e195e2d587e6a8691d5ed005f

**Comment by alifbe** [comment]
You are probably right.

For this tool (csv2ofmvol), is there any specific date format that we can use? I see ``pd.to_datetime`` has optional argument ``format`` which can be used to avoid ambiguity.

**Comment by berland** [comment]
This tool tries to accomodate to vol-files with non-ISO date formats (which we really should avoid, we should only use the date format ISO-8601 everywhere we can). I guess the tests covers the needs, so as long as you pass the tests with changed code, it should be fine.
