### ISSUE TITLE
Unpin numpy

### ISSUE THREAD

**Issue by alifbe** [equinor/subscript#532]
Numpy 1.24.3 seems to have issue with xtgeo. ``xtgeo.gridproperty_from_file()`` gives strange results with numpy 1.24.3

It needs to be unpinned when the issue is resolved.

**Comment by kwinkunks** [comment]
Seems like issue has been resolved in NumPy, slated for 1.24.4 milestone https://github.com/numpy/numpy/issues/23651

**Comment by alifbe** [comment]
Thanks. You are right, the issue is resolved now with update on NumPy and xtgeo.

This is now resolved with PR #542
