### ISSUE TITLE
pack_sim issue with comments after main commands

### ISSUE THREAD

**Issue by RezaeiDoust** [equinor/subscript#538]
As obvious, Eclipse DATA file is separated into sections by commands like "RUNSPEC, GRID, EDIT, PROPS, REGIONS, SOLUTION, SUMMARY and SCHEDULE.

when -fmu option is selected and pack_sim is supposed to put include files after each section into a folder by the same section name,

if any comments is entered after these commands, it will not be recognized. for example:

GRID  -- comment

is not recognized and the files will be added to the previous section if that one is recognized. if all the main sections have comment, then the result is not very understandable.

**Comment by alifbe** [comment]
Resolve with PR #544
