### ISSUE TITLE
`pack_sim` wrongly adds an extra INCLUDE

### ISSUE THREAD

**Issue by rnyb** [equinor/subscript#583]
When running `pack_sim` an extra INCLUDE keyword is added for all INCLUDE statements causing an error when run with Eclipse

![image](https://github.com/equinor/subscript/assets/51825893/4cf779ae-2ebc-4669-b546-16c6d5ae29ce)

**Comment by FarokhShoaei** [comment]
i have not specified the Komodo version so it is the default

**Comment by mferrera** [comment]
@FarokhShoaei thanks! Just to clarify-- the default Komodo stable, or the default subscript as installed directly from here?

**Comment by FarokhShoaei** [comment]
default Komodo stable

**Comment by rnyb** [comment]
One can check version by running `pack_sim --version`
On current komodo stable {2023.06.06-py38} the output should look like this:  `pack_sim.py (subscript version 0.16.5)`

**Comment by rnyb** [comment]
This bug appears when there is a comment line in between INCLUDE and it's argument - see example pic below
Note: when there is no comment line in between it looks ok.

![image](https://github.com/equinor/subscript/assets/51825893/6922d589-12b8-4500-9daa-0b8af87e6b0d)

**Comment by rnyb** [comment]
Another thing, when re-running `pack_sim`, the output DATA file is not overwritten. We should consider changing this behavior so that it overwrites existing files. However, if written to same folder as input file then it should probably give a warning (or error) before proceeding to avoid overwriting original data file

**Comment by asnyv** [comment]
A thought:

It is possible to parse an eclipse DATA-file with the opm package, and write it to a file afterwards. 
Using this would probably drastically simplify `pack_sim`, which of course is beneficial from a maintenance point of view.

The BIG disadvantages are that I think all files will be merged into one (including include files) in the export, so the DATA-file will get loooong, and I think all comments will disappear as the opm parser doesn't care about comments. 

Considering the disadvantages, I am definitely not sure that it is a good idea to make this change, but could maybe be worth a thought to minimize our technical debt in subscript.

**Comment by alifbe** [comment]
> A thought:
> 
> It is possible to parse an eclipse DATA-file with the opm package, and write it to a file afterwards. Using this would probably drastically simplify `pack_sim`, which of course is beneficial from a maintenance point of view.
> 
> The BIG disadvantages are that I think all files will be merged into one (including include files) in the export, so the DATA-file will get loooong, and I think all comments will disappear as the opm parser doesn't care about comments.
> 
> Considering the disadvantages, I am definitely not sure that it is a good idea to make this change, but could maybe be worth a thought to minimize our technical debt in subscript.

@asnyv That's a cool feature. Although the disadvantage is rather big as you pointed out. Having it in a big long file will make it difficult to use in FMU context. Perhaps we can have it as an alternative? May be allow user to switch to `opm` mode if they have issue with the current `pack_sim`

**Comment by alifbe** [comment]
Solve in #586
