### ISSUE TITLE
New script for merging UNRST files

### ISSUE THREAD

**Issue by rnyb** [equinor/subscript#627]
On Drogon we have implemented a forward model to merge Eclipse restart files (UNRST) from history and prediction. This is very convenient in cases of post-processing, where one need to make diffs across pred and hist (for instance for seismic feasibility studies or to make pressure/saturation diff maps). We should consider including this in subscript to remove the need for local copies.

**Comment by asnyv** [comment]
I definitely see the use case and I'm generally supporting that we should minimize the number of non-standard jobs in Drogon, but must admit I'm a bit worried about the consumption of disk space if it becomes standard to copy the full history for UNRST files (which of course is one of the main "disk thieves").

Of course, making it available doesn't mean that everyone has to do it, and one could also delete it directly after making the "diffs" as part of the workflow, but things like these tend to be added workflows and then never removed...

Could it be possible to solve this in a different way (even though it probably is more challenging to implement originally)?
E.g. make the jobs creating the diffs support multiple UNRST files?

**Comment by rnyb** [comment]
> Could it be possible to solve this in a different way (even though it probably is more challenging to implement originally)? E.g. make the jobs creating the diffs support multiple UNRST files?

This was the intiial solution attempted, but it turned out be a challenging to change all the xtgeo functionality to handle this. However, this may be a viable long term solution.

**Comment by asnyv** [comment]
> > Could it be possible to solve this in a different way (even though it probably is more challenging to implement originally)? E.g. make the jobs creating the diffs support multiple UNRST files?
> 
> This was the intiial solution attempted, but it turned out be a challenging to change all the xtgeo functionality to handle this. However, this may be a viable long term solution.

ok 🤔 Makes sense that supporting multiple files in the core of xtgeo is a big job. 
Could e.g. the diff jobs temporarily merge the files themselves prior to sending the file to xtgeo? Then xtgeo sees a single file as it technically exists for a short period of time, but without risking permanent storage. 
Just throwing out ideas here 😅
