### ISSUE TITLE
pack_sim does not handle comment lines between INCLUDE and <includefile>

### ISSUE THREAD

**Issue by erlid** [equinor/subscript#695]
See example below; `pack_sim`'ed DATA file to the left - original DATA file to the right
![image](https://github.com/equinor/subscript/assets/57486677/4c15b2d1-0bdd-458e-906d-631bf437dc7d)

**Comment by alifbe** [comment]
Hi @erlid 

This looks like something that PR #586  was trying to solve.

I also didn't manage to reproduce the issue with my test data. 

Can you please check if you are using the latest `pack_sim` version? The bug fix should be available from version 0.17.1

**Comment by erlid** [comment]
Sorry false alarm. I was working with a model in an old komodo.
